# Generated by Django 2.1.7 on 2019-04-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingAuthServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_profile',
        ),
    ]
