# Generated by Django 2.1.7 on 2019-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingAuthServer', '0002_auto_20190426_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
