# Generated by Django 2.1.7 on 2019-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingAuthServer', '0004_auto_20190426_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
