# Generated by Django 2.1.7 on 2019-04-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingAuthServer', '0005_auto_20190426_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.IntegerField(unique=True),
        ),
    ]
