# Generated by Django 2.1.7 on 2019-04-26 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FolderingAuthServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FolderManagers', to='FolderingAuthServer.User')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uid', models.IntegerField()),
                ('data_url', models.TextField()),
                ('folder_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FolderData', to='FolderingFolderServer.Folder')),
            ],
            options={
                'ordering': ['folder_uid'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FolderMember', to='FolderingFolderServer.Folder')),
                ('user_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FolderMember', to='FolderingAuthServer.User')),
            ],
            options={
                'ordering': ['folder_uid'],
            },
        ),
    ]
