# Generated by Django 2.1.7 on 2019-04-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingFolderServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/default_image.jpeg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='data_url',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='data_type',
            field=models.CharField(default='text', max_length=45),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_name',
            field=models.CharField(default='token', max_length=45),
        ),
        migrations.AddField(
            model_name='text',
            name='folder_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textData', to='FolderingFolderServer.Folder'),
        ),
        migrations.AddField(
            model_name='link',
            name='folder_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkData', to='FolderingFolderServer.Folder'),
        ),
        migrations.AddField(
            model_name='image',
            name='folder_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageData', to='FolderingFolderServer.Folder'),
        ),
    ]
