# Generated by Django 2.2 on 2019-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingFolderServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='image',
            field=models.ImageField(default='media/default_image.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='folder',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
