# Generated by Django 2.1.7 on 2019-04-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingFolderServer', '0002_auto_20190426_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_name',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='data_type',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
