# Generated by Django 2.1.7 on 2019-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingFolderServer', '0003_auto_20190426_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
