# Generated by Django 2.2 on 2019-04-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingFolderServer', '0005_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='FolderingFolderServer.Folder'),
        ),
        migrations.AddField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='FolderingFolderServer.Folder'),
        ),
        migrations.AddField(
            model_name='text',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='FolderingFolderServer.Folder'),
        ),
    ]
