# Generated by Django 2.2 on 2019-05-17 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FolderingFolderServer', '0006_auto_20190412_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FolderingFolderServer.Folder'),
        ),
        migrations.AlterField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='FolderingFolderServer.Folder'),
        ),
        migrations.AlterField(
            model_name='text',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='FolderingFolderServer.Folder'),
        ),
    ]
