# Generated by Django 2.2 on 2019-05-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingFolderServer', '0007_auto_20190517_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='author',
        ),
    ]
