# Generated by Django 2.2 on 2019-05-17 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FolderingFolderServer', '0008_remove_folder_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
