# Generated by Django 2.2 on 2019-05-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FolderingFolderServer', '0009_folder_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('userImage', models.ImageField(default='media/default_image.jpeg', null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='folder',
            name='author',
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='FolderingFolderServer.User'),
        ),
    ]
